### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by d1ret** [benbaker76/SimpleHIDWrite#1]
Trying build from source code, and programm not work...
"devce can not be opened" in JvHidControllerClass

**Comment by d1ret** [comment]
Fixed

**Comment by benbaker76** [comment]
What was the fix if you don't mind me asking?

**Comment by d1ret** [comment]
If you use JvHidControllerClass , HID.pas and DBT.pas which are attached to the project, then after the build the application cannot access the devices. I removed them from the project and installed new versions of the modules

Also thank for this source - code, was very helpful with learning usb requests for my project
